name: Generate AI Fortune Posts

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'  # UTC 기준, KST 09:00/13:00/17:00/21:00/01:00/05:00
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Set up environment
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
      - name: Write service account key
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > key.json
      - name: Run AI Post Generator
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/key.json
        run: node scripts/generateAIPost.cjs
